# Generated by Django 4.1.5 on 2023-02-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApi', '0003_alter_tareas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='status',
            field=models.CharField(choices=[('1', 'Realizado'), ('2', 'No Realizado'), ('3', 'En Proceso')], default='1', max_length=30),
        ),
    ]
