# Generated by Django 4.1.5 on 2023-02-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApi', '0004_alter_tareas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='status',
            field=models.CharField(choices=[('Realizado', 'Realizado'), ('No Realizado', 'No Realizado'), ('En Proceso', 'En Proceso')], default='Realizado', max_length=50),
        ),
    ]
