# Generated by Django 4.1.5 on 2023-02-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareasApi', '0006_alter_tareas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='status',
            field=models.CharField(choices=[('Realizado', '1'), ('No Realizado', '2'), ('En Proceso', '3')], default='Realizado', max_length=50),
        ),
    ]
